CREATE SCHEMA IF NOT EXISTS ime;

CREATE TABLE ime.category (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ime.question_answer (
    id INTEGER PRIMARY KEY,
    category INTEGER REFERENCES ime.category,
    question VARCHAR(255) NOT NULL,
    answer VARCHAR(255) NOT NULL,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
