spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    r2dbc:
      repositories:
        enabled: true
  flyway:
    baseline-on-migrate: true
    default-schema: ime
